[package]
name = "bencode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bstr = "1.9"
derive_more = "0.99"
format-bytes = "0.3"
peg = "0.8"
serde = "1.0"
